# Generated by Django 4.1 on 2022-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='https://m.media-amazon.com/images/I/71wqzv-M41L._SL1500_.jpg', upload_to=''),
        ),
    ]
